### ISSUE TITLE
Field is still in toString

### ISSUE THREAD

**Issue by Rainer-Lang** [square/auto-value-redacted#12]
I made all what's in the readme:
1) added extension to project
2) defined the annotation
3) used the annotation
rebuild project -> field is still in auto-value-generated toString()

using AutoValue 1.2-rc1
I'm also using the extension auto-value-parcel

**Comment by JakeWharton** [comment]
There is not enough information here for this report to be actionable. Can
you provide a sample project which demonstrates the problem?

**Comment by Rainer-Lang** [comment]
I will prepare something.

**Comment by Rainer-Lang** [comment]
@JakeWharton Shared a bitbucket repo via email

**Comment by JakeWharton** [comment]
When I run `./gradlew clean build` on your project, `app/build/generated/source/apt/debug/` shows `com/example/example/` having 3 generated classes:

 * `$$AutoValue_TestAutoValue` which extends `TestAutoValue` (your class) which has the normal `toString()`.
 * `$AutoValue_TestAutoValue` which extends `$$AutoValue_TestAutoValue` which has the redacted `toString()` overriding the normal one.
 * `AutoValue_TestAutoValue` which extends `$AutoValue_TestAutoValue` which contains the parcel implementation.

If you create an instance by calling `new AutoValue_TestAutoValue(..).toString()` you should see the redacted `toString()` being used.

**Comment by Rainer-Lang** [comment]
@JakeWharton I never looked in ```$AutoValue_TestAutoValue```. It was my fault.
Thanks a lot for your effort.
