### ISSUE TITLE
Compilation Breaks if using bean-style getters

### ISSUE THREAD

**Issue by toadzky** [square/auto-value-redacted#13]
I have a class representing a person with a field I want redacted. It's a class being used for Android data binding, so it requires bean-style getters. The `@Redacted` extension generates a `toString()` implementation that assumes the more fluent style getters, which throws an error on compilation.

![image](https://cloud.githubusercontent.com/assets/2286682/15005231/dd2806d6-117e-11e6-8902-d65f240d9df9.png)

![image](https://cloud.githubusercontent.com/assets/2286682/15005227/c9ed73e4-117e-11e6-9fee-2af5f63238ff.png)

**Comment by JakeWharton** [comment]
Yeah this is an easy fix. I discovered this bug and fixed it in the
parcelable extension a while back... guess we weren't using redacted on
that one.
