### ISSUE TITLE
Problem while using toBuilder()

### ISSUE THREAD

**Issue by suraj1291993** [square/auto-value-redacted#21]
I am having problem while creating AutoValue with `@Redacted` . The sample code is

`@AutoValue
abstract class Animal {
    @Redacted abstract String name();
    abstract int numberOfLegs();

    abstract Builder toBuilder();

    static Builder builder() {
        return new AutoValue_Animal.Builder();
    }

    @AutoValue.Builder
    abstract static class Builder {
        abstract Builder setName(String value);
        abstract Builder setNumberOfLegs(int value);
        abstract Animal build();
    }
}`

**Comment by JakeWharton** [comment]
And what's the problem?

**Comment by suraj1291993** [comment]
The error I am getting is

> Error:(101, 14) java: constructor AutoValue_Animal in class com.AutoValue_Animal cannot be applied to given types;
  required: java.lang.String,int,com.Animal.Builder
  found: java.lang.String,java.lang.Integer
  reason: actual and formal argument lists differ in length

and

> Error:(8, 5) java: constructor $AutoValue_Animal in class com.$AutoValue_Animal cannot be applied to given types;
  required: java.lang.String,int
  found: java.lang.String,int,com.Animal.Builder
  reason: actual and formal argument lists differ in length

The generated classes can be found [here](https://pastebin.com/ECE13nL9)

**Comment by suraj1291993** [comment]
It seems the issue was on my side. After I updated the version of auto-value I am not getting this error.
