### ISSUE TITLE
Add support for incremental annotation processing by implementing new AutoValueExtension API

### ISSUE THREAD

**Issue by bingranl** [square/auto-value-redacted#22]
Auto Value supports incremental annotation processing in 1.6.3-rc1. auto-value-redacted can implement new API to support incremental annotation processing.

**Comment by bingranl** [comment]
@mattprecious Hi Matthew, do you consider making auto-value-redacted support incremental annotation processing?

**Comment by JakeWharton** [comment]
PR welcome

**Comment by bingranl** [comment]
Please take a look at my PR, thanks!!
