### ISSUE TITLE
Support for Generic Class

### ISSUE THREAD

**Issue by suraj1291993** [square/auto-value-redacted#24]
When I am using a generic class, there was problem in generated class which causes compilation problem.
Say, my code is
```
@AutoValue
public abstract class TestUser<T> {
	@Redacted
	public abstract String name();
	public static <T> Builder<T> builder() {
		return new AutoValue_TestUser.Builder<>();
	}
	@AutoValue.Builder
	public abstract static class Builder<T> {
		public abstract Builder<T> name(String name);
		public abstract TestUser<T> build();
	}
}
```
But, the generated code will should have class looks like 
```
final class AutoValue_TestUser extends $AutoValue_TestUser {
  AutoValue_TestUser(String name) {
    super(name);
  }
  @Override
  public final String toString() {
    return "TestUser{"
        + "name=██"
        + '}';
  }
}
```
But it should have been 
`final class AutoValue_TestUser<T> extends $AutoValue_TestUser<T>`

auto-value - 1.6.5
auto-value-redacted - 1.1.0

Any help regarding this is much appreciated.

**Comment by mattprecious** [comment]
This likely requires a code change. I don't think generics were considered when writing this.

https://github.com/square/auto-value-redacted/blob/master/src/main/java/com/squareup/auto/value/redacted/AutoValueRedactedExtension.java#L63-L68
